export const gameConstants = {
    FETCH_GAME_REQUEST:'FETCH_GAME_REQUEST',
    FETCH_GAME_SUCCESS:'FETCH_GAME_SUCCESS',
    FETCH_GAME_FAILURE:'FETCH_GAME_FAILURE',

    CREATE_REQUEST: 'GAME_CREATE_REQUEST',
    CREATE_SUCCESS: 'GAME_CREATE_SUCCESS',
    CREATE_FAILURE: 'GAME_CREATE_FAILURE',
 
    DELETE_REQUEST: 'GAME_DELETE_REQUEST',
    DELETE_SUCCESS: 'GAME_DELETE_SUCCESS',
    DELETE_FAILURE: 'GAME_DELETE_FAILURE'   
}